# The target folder of following command, actually is the folder generated by mvn command
# webapp-runner.jar defined as plugin in pom.xml, which will create dependency folder under target folder after invoking command of mvn package
web: java $JAVA_OPTS -jar target/dependency/webapp-runner.jar --port $PORT target/*.war